### ISSUE TITLE
Custom-Domain für Cyberland

### ISSUE THREAD

**Issue by dasniko** [jugda/registration#19]
- Eintrag in Route 53 für eine ijug.de Subdomain für die Registrierung
- SSL-Zertifikat in ACM
- Mapping Custom-Domain auf API-Gateway

**Comment by dasniko** [comment]
Welche Subdomain wollen wir verwenden?

**Comment by dasniko** [comment]
Subdomain in AWS konfiguriert, muss nun in das DNS der Root-Domain eingetragen werden, damit das an AWS delegiert wird.

**Comment by ascheman** [comment]
Subdomain Delegierung bei iJUG Office / IT angefragt.

**Comment by dasniko** [comment]
Subdomain ist konnektiert, konfiguriert, etc. muss jetzt noch durch alle DNS Replikationen durch. Je nach VPN-Verbindung bekomme ich schon eine Auflösung, bei manchen noch nicht. Grundsätzlich aber alles ok. 👍
