### ISSUE TITLE
Cyberland events.json

### ISSUE THREAD

**Issue by dasniko** [jugda/registration#24]
@sippsack Kannst Du für die Cyberland Website so ein Events-JSON generieren, wie wir bei der JUG DA haben? Gleiche Struktur...

**Comment by sippsack** [comment]
Eine initiale Fassung ist da: https://cyberland.ijug.eu/events.json

**Comment by dasniko** [comment]
Die Registrierung nutzt das Feld "summary" aus dem JSON (siehe https://www.jug-da.de/events.json), da steht zusätzlich zum Titel noch der Speaker (oder die Speaker) drin. Wenn die Cyberland keine Speaker als solches hat, dann ggf. einfach Titel duplizieren?
Die "meetupId" ist für die Registrierung nicht notwendig, das Mapping zielt immer auf die eventId ab, die Bestandteil der "uid" ist und über die entsprechende "eventId" dann in den Registrierungs-URL Query-Params angegeben wird.

**Comment by sippsack** [comment]
Habe die events.json nochmal angepasst: https://cyberland.ijug.eu/events.json

**Comment by dasniko** [comment]
Tickets gerne erst nach Review von einem Couterpart schließen.

Anpassung ist ok.

**Comment by dasniko** [comment]
Ich muss es leider noch mal aufmachen...

`"start": "2021-03-16 20:00",`

Hier muss ein gültiges ISO-Format drin sein, also möglichst:

`"start": "2021-03-16T20:00:00",`

**Comment by sippsack** [comment]
Hab es angepasst: https://cyberland.ijug.eu/events.json

**Comment by dasniko** [comment]
Jetzt scheint alles zu passen. Danke.
