### ISSUE TITLE
Meeting-Vorschaltseite für Cyberland

### ISSUE THREAD

**Issue by dasniko** [jugda/registration#25]
@sippsack Bitte die Meeting-Vorschaltseite für die Cyberland entsprechend anpassen und mir die Vorlage dann zu Verfügung stellen, damit ich das implementieren kann.

**Comment by sippsack** [comment]
Hast Du zufällig einen Screenshot oder eine Fake-Seite? Ich kann keine Vorschaltseite ohne Event aufrufen. Oder übersehe ich da etwas?

**Comment by dasniko** [comment]
https://jvm-german.slack.com/archives/G01NAH9KUJC/p1613227883061300

**Comment by sippsack** [comment]
Habe einen ersten Entwurf fertig gemacht. Es kompiliert, konnte es aber lokal nicht ausprobieren.

**Comment by dasniko** [comment]
"es kompiliert" ist kein Kriterium, das Ticket zu schließen.
Ich schaue es mir die Tage an.
