### ISSUE TITLE
Customize registration period

### ISSUE THREAD

**Issue by sippsack** [jugda/registration#33]
Default registration period opens  1 month before event date. Please customize this value with an parameter ("opensMonthsBefore").

**Comment by sippsack** [comment]
Possible solution:

@GET
    public TemplateInstance getForm(@QueryParam("eventId") String eventId,
                                    @QueryParam("limit") @DefaultValue("60") int limit,
                                    @QueryParam("showPub") @DefaultValue("false") boolean showPub,
                                    @QueryParam("deadline") String deadline,
                                    @QueryParam("opensMonthsBefore") @DefaultValue("1") int opensMonthsBefore) {
        if (deadline == null) {
            deadline = eventId + "T18:00:00+02:00";
        }
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime deadlineTime = LocalDateTime.parse(deadline, DateTimeFormatter.ISO_DATE_TIME);
        LocalDate startDate = LocalDate.parse(eventId).minusMonths(opensMonthsBefore);

**Comment by dasniko** [comment]
Where's the PR?

**Comment by dasniko** [comment]
Feature has been deployed for both tenants!
