### ISSUE TITLE
Setup CI with GitHub Actions

### ISSUE THREAD

**Issue by dasniko** [jugda/registration#39]

**Comment by dasniko** [comment]
I've just added a [default YAML file ](https://github.com/jugda/registration/blob/c29f832ec75e44583a20b7b4440d85e932c800be/.github/workflows/maven.yml)for building the project with a GitHub Maven Action.

The build fails because the testcontainer can not be started.
Do I miss anything? Permissions? Special commands?

I'm new to GitHub actions, so any help is appreciated.
@ascheman ? @sippsack ?

**Comment by sippsack** [comment]
I have no experience with GitHub Actions. Running Out of disk space may be a problem with the free tier. But I don't know.
