### ISSUE TITLE
Benachrichtigung wenn das Event fast voll ist

### ISSUE THREAD

**Issue by sippsack** [jugda/registration#4]
z. B. bei mehr als 95 % eine E-Mail oder Slack-Nachricht verschicken

**Comment by dasniko** [comment]
Slack-Nachricht gefällt mir 👍

**Comment by dasniko** [comment]
Ist etwas blöd, da die Anwendung bei der Registrierung nicht mehr "weiß", wieviele Teilnehmer sich anmelden dürfen, nur zum Zeitpunkt der Formular-Anzeige über die URL.
Dafür müssen wir den `seatCount` mit durchschleifen...
