### ISSUE TITLE
Calendar-Anhang

### ISSUE THREAD

**Issue by pilhuhn** [jugda/registration#41]
Als Zusatz zu #40: Wenn möglich sollte eine .iCal/.ics/... Datei im Anhang mitgesendet werden, welche die relevanten Details zum Termin enthält, so dass die Teilnehmer sehr einfach einen Eintrag in ihrem Kalender machen können.

**Comment by ascheman** [comment]
Offener Punkt: Der Link zum Meeting wird erst kurz vor dem Meeting per Mail an die Teilnehmer verschickt. Daher kann er in der Bestätigung leider noch nicht enthalten sein.

**Comment by pilhuhn** [comment]
Ich denke es sollte möglich sein, in der zweiten Mail nochmals die .iCal-Datei , nun aber mit Link, zu versenden. Gmail/gCal sollten das dann auch automatisch aktualisieren.

**Comment by dasniko** [comment]
Da wir nie den endgültigen Link versenden, sondern "nur" einen Link auf unsere Vorschaltseite, über die man dann auf das eigentliche Meeting/Seite gelangt, könnte man auch die URL der Vorschaltseite direkt in den Kalendereintrag packen. Diese ist deterministisch, bietet aber nur am Veranstaltungstag die entsprechenden Inhalte an.
