### ISSUE TITLE
Google Kalenderlink in Terminen einfügen

### ISSUE THREAD

**Issue by swschilke** [jugda/registration#42]
Hallo bitte bei den JUGDA Termine einen Google Kalenderlink einfügen

Also einen Kalender Link den Google versteht (ics versteht der ja nicht (wirklich)). 

Sowas wie hier (Beispiel) https://pod.events/event/get-ready-to-launch-your-podcast-successfully-2
wäre nett.  Also so in der Art https://calendar.google.com/calendar/r/eventedit?text=Get+Ready+to+Launch+Your+Podcast+Successfully%21&dates=20220525T160000Z/20220525T170000Z&details=Launching+a+podcast+can+be+scary%2C+exciting%2C+stressful%2C+fun%2C+and+so+much+more%2C+especially+if+you%27ve+never+done+anything+like+this+before%21+That%27s+why+we%27re+having+this+webinar+-+to+remove+the+stressful+parts%2C+and+concentrate+on+the+fun+side%21%0D%0A%0D%0ASo+what+will+you+learn%3F+We%27re+going+to+look+at+three+core+parts+of+launching+your+podcast%3A%0D%0A%0D%0A-+Pre-launch%3A+ideation%2C+research%2C+and+goals%0D%0A-+Pre-publish%3A+assets%2C+episodes%2C+equipment%2C+host%0D%0A-+Launch%3A+Setting+your+show+live%2C+distribution%2C+promo%0D%0A%0D%0Ahttps%3A%2F%2Fyoutu.be%2Fz9THMIM9GPg&location=%28Virtual+event%29

Wie hier beschrieben https://dev.to/rinkiyakedad/creating-an-add-event-to-google-calendar-link-for-your-project-52c1

Danke

**Comment by ascheman** [comment]
Haben wir schon:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/456000/169002659-28c98a19-a311-4838-8e2b-dfd22f83b3bd.png">

**Comment by ascheman** [comment]
Oh, sorry, @swschilke, du willst einen zweiten Link, der von Google Calendar direkt verstanden wird ...

**Comment by swschilke** [comment]
Genau und der ics scheint auch buggy zu sein, da er sich entweder gar nicht oder erst nal mehrmaligem Klicken oder langem warten öffnet. Danke

**Comment by dasniko** [comment]
Der vorhandene ICS-Krams ist nicht buggy, den haben wir damals extra mit mehreren ICS-Validatoren gegen die Spec geprüft. Es sei denn, es hat sich in den letzten 2 Jahren was an der Spec geändert, oder die Validatoren waren fehlerhaft.

Aber ich bin für PRs offen.

**Comment by dasniko** [comment]
@swschilke Ich habe gerade mal einen ersten Wurf auf den Event-Seiten implementiert, schau's Dir doch mal an und gib ein Feedback. Danke.

**Comment by dasniko** [comment]
Kein Feedback?

**Comment by swschilke** [comment]
Sorry untergegangen, öffnet sich, sieht okay aus. Danke

Niko Köbler ***@***.***> schrieb am Sa., 16. Juli 2022, 13:59:
